# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-14 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myurlex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandedurl',
            name='timestamp',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='expandedurl',
            name='waybackUrl',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='expandedurl',
            name='origin',
            field=models.URLField(default='http://'),
        ),
    ]
