# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myurlex', '0002_auto_20160813_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandedurl',
            name='imageUrl',
            field=models.URLField(default=''),
        ),
    ]
