# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myurlex', '0003_expandedurl_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandedurl',
            name='imageId',
            field=models.IntegerField(default=0),
        ),
    ]
